name: data
on:
  schedule:
    - cron: 5 6 * * *
  workflow_dispatch: {}
  push:
    paths:
      - .github/workflows/flat.yml
jobs:
  scheduled:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Pull from main
        run: |-
          git pull
      - name: Fetch current-federal
        run: curl -fsSL -o current-federal.csv "https://manage.get.gov/api/v1/get-report/current-federal"
      - name: Fetch current-full
        run: curl -fsSL -o current-full.csv "https://manage.get.gov/api/v1/get-report/current-full"
      - name: Commit updated data
        run: |
          git config user.name "botgov"
          git config user.email "help@get.gov"
          git add current-federal.csv current-full.csv
          git commit -m "Latest data ($(date -u +%FT%TZ))" || exit 0
          git push
